### PR TITLE
ajinkya made changes

### PR DESCRIPTION
**Pull request by ajinkyak423**
fixed first issue

### CODE REVIEW

**Review by Suyash-Purwar — CHANGES_REQUESTED** [review]
Hello @ajinkyak423

Please add a comma after the key-value pair at line 6. Add a comma after the GitHub URL just like it's done in above key-value value pairs. But don't put comma after the LinkedIn URL.

**Comment by ajinkyak423** [comment]
Thank you @Suyash-Purwar

It's really good to know you put in the time to look into my first issue fixing it was really nice of you. 
Thank you 😊

**Comment by Suyash-Purwar** [comment]
No problem mate! 😄

**Comment by Abhishek-kumar09** [comment]
Thanks for the review @Suyash-Purwar 
Thanks @ajinkyak423  for your PR, Welcome to the community!! Goodluck with Open source!

**Pull request merged**
