### PR TITLE
Learned to Contribute

### PR DESCRIPTION
**Pull request by yashss1**
New to Community, Exploring new things,
Would be glad on any beginner's suggestions.

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
Great @yashss1, thanks for your PR.
 > Would be glad on any beginner's suggestions.
 
 Do you like  working with react, we have created a new project here: https://github.com/codeforcauseorg/Certificate-generator-react
 
 and we already have codeforcause/codeforcause website, that is also written in react.

**Comment by yashss1** [comment]
Thank you @AAbhishek-kumar09, I would like to work, But I have to learn a bit about it first.
It would be a great opportunity for me and I would need some time. 
Is there any dead-line or so in contributing to it ?

**Comment by yashss1** [comment]
Thank you @Abhishek-kumar09, I would like to work, But I have to learn a bit about it first.
It would be a great opportunity for me and I would need some time. 
Is there any dead-line or so in contributing to it ?

**Comment by Abhishek-kumar09** [comment]
@yashss1 
> Is there any dead-line or so in contributing to it ?

Not at all, take your time.You can contribute anytime on any phase.

**Pull request merged**
