### PR TITLE
Aman made changes

### PR DESCRIPTION
**Pull request by Amanduttbhagat**

### CODE REVIEW

**Review by Suyash-Purwar — CHANGES_REQUESTED** [review]
Hey @Amanduttbhagat 

You have pushed two files for your own data. Please delete either one of them and your PR will be merged soon.
And also you made changes to `saksham.json` file which is not allowed. But, since you have only removed extra lines in the end, it may get accepted.

**Comment by Amanduttbhagat** [comment]
Hello @Suyash-Purwar 
Actually this was my first time contributing and I was a bit confused and accidentally made these changes, I am gonna make a new Pull Request.

**Comment by Suyash-Purwar** [comment]
That's alright!
Instead of opening a new PR, you can make commits to this PR. It'll be better.
Close this pull request if you are going to open new one.

**Comment by Amanduttbhagat** [comment]
ok thanks :)

**Comment by Amanduttbhagat** [comment]
one more thing,
after I made the pull request all the integration test failed why,

and when I used this command :
$ git push origin temp

every time I get this,

To https://github.com/Amanduttbhagat/pledge.git
 ! [rejected]        temp -> temp (non-fast-forward)
error: failed to push some refs to 'https://github.com/Amanduttbhagat/pledge.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Pull request closed without merging**
