### PR TITLE
Added my information(sam.json)

### PR DESCRIPTION
**Pull request by TheSamarthShah**
hey please merge my pull request i have added my information.

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
hey @TheSamarthShah , thanks for your PR. Welcome to the community.

**Comment by TheSamarthShah** [comment]
> hey @TheSamarthShah , thanks for your PR. Welcome to the community.

My pleasure brother

**Comment by TheSamarthShah** [comment]
> hey @TheSamarthShah , thanks for your PR. Welcome to the community.

If you have any other work I can do. But web development related 😅

**Comment by Abhishek-kumar09** [comment]
Ofcourse you can contrbute to many open source projects, like click-short, certificate-generator, codeforcause.org website or desktop app if you like. 
click-short, certificate-generator: they are very new projects and are at the beginning of development ,if you like to test them out you could. Feel free to ask any doubt you come across.

**Comment by TheSamarthShah** [comment]
> @TheSamarthShah 
> Ofcourse you can contrbute to many open source projects, like click-short, certificate-generator, codeforcause.org website or desktop app if you like. 
> click-short, certificate-generator: they are very new projects and are at the beginning of development ,if you like to test them out you could. Feel free to ask any doubt you come across.

Sure I'll check that out tomorrow morning 🙂. I would like to work.

**Pull request merged**
