### PR TITLE
New contributor

### PR DESCRIPTION
**Pull request by Devenkapoor7303**

### CODE REVIEW

**Review by Suyash-Purwar — CHANGES_REQUESTED** [review]
Hey  @Devenkapoor7303 

Other than adding your details in the JSON file, you have also updated two Node.js dependencies. You don't have the permission to change those.

Dependencies changed are:

- `gatsby`
- `gatsby-plugin-sharp`

Please revert those changes and your PR will be merged after reviewing by the managers of this project.

**Comment by Devenkapoor7303** [comment]
Thank u @Suyash-Purwar  for the help.

**Comment by Suyash-Purwar** [comment]
No problem!

**Comment by Abhishek-kumar09** [comment]
Thanks @Devenkapoor7303 for your PR, Welcome to the community!

**Pull request merged**
