### PR TITLE
add preloader

### LINKED ISSUE #21: Add interactive loader
Add an interactive loader that matches with the current theme of the webpage.

### PR DESCRIPTION
**Pull request by urvashigupta7**
Fixes #21

### CODE REVIEW

**Comment by urvashigupta7** [comment]
@KeenWarrior @GangaChatrvedi Please review 😄

**Comment by GangaChatrvedi** [comment]
Preloader gif is not matching the theme. Lemme collect a matching gif from designer.

**Comment by GangaChatrvedi** [comment]
[loading-opaque.zip](https://github.com/codeforcauseorg/pledge/files/4836645/loading-opaque.zip)

Here is the image that you can use.

And also on load, loader first comes to the left then to the center. Can you please look at this

**Comment by urvashigupta7** [comment]
@GangaChatrvedi I have made the changes 😄. I hope it works fine now.

**Comment by GangaChatrvedi** [comment]
This looks fine @urvashigupta7 . Thanks

**Pull request merged**
