### PR TITLE
New contributor Information - Rajdeep Ghosh

### PR DESCRIPTION
**Pull request by rajdeep-ghosh**
Added my profile information RajdeepGhosh.json

### CODE REVIEW

**Comment by rajdeep-ghosh** [comment]
Please accept my PR

**Comment by rajdeep-ghosh** [comment]
Git is fun!

**Review by rajdeep-ghosh — COMMENTED** [review]
LGTM!

**Comment by Abhishek-kumar09** [comment]
Please revert those image changes, since this particular PR should concern about adding new contributor.

**Comment by rajdeep-ghosh** [comment]
@Abhishek-kumar09 Sure. I will close this PR and make a new one.

**Pull request closed without merging**
