### PR TITLE
My first contribution

### PR DESCRIPTION
**Pull request by Adithya-K-Shetty**

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
Thanks @Adithya-K-Shetty for your PR, Welcome to the community.

**Comment by Adithya-K-Shetty** [comment]
thanks for giving an opportunity to contribute

**Comment by Adithya-K-Shetty** [comment]
how  to view the result

**Comment by Abhishek-kumar09** [comment]
You can view your contributor card here: https://pledge.codeforcause.org/

**Pull request merged**
