### PR TITLE
Hey there, I made some changes

### PR DESCRIPTION
**Pull request by PrajwalG22**
New here, Would love some guidance

### CODE REVIEW

**Review by Suyash-Purwar — CHANGES_REQUESTED** [review]
Hey @PrajwalG22!

At line 6, after the github URL you have added a comma which is causing error. Please remove it and soon your PR be merged by the maintainers of this project.

Thanks!

**Comment by PrajwalG22** [comment]
Thank you so much. I appreciate and sorry for my little mistake

**Review by PrajwalG22 — COMMENTED** [review]
Corrected a little mistake

**Comment by Suyash-Purwar** [comment]
Hey! You forgot to enclose the key-value pair inside curly braces. Put everything inside `{}`.

**Comment by PrajwalG22** [comment]
Need some progress

**Pull request closed without merging**
